export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    onlineUsers: (orgId: string) => ['online-users', orgId] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    typing: (sessionId: string) => ['typing', sessionId] as const,
    me: ['me'] as const,
    userPreferences: ['user-preferences'] as const,
    // identityCandidates removed — approval candidates use queryKeys.approvals(...)
    identityPersons: (orgId?: string | null, q?: string | null) => ['identity-persons', orgId ?? null, q?.trim() ?? ''] as const,
    identityPersonDetail: (orgId?: string | null, personId?: string | null) => ['identity-person-detail', orgId ?? null, personId ?? null] as const,
    identityAudits: (
        orgId?: string | null,
        personId?: string | null,
        identityId?: string | null,
    ) => ['identity-audits', orgId ?? null, personId ?? null, identityId ?? null] as const,
    teamMemoryCandidates: (orgId?: string | null, status = 'pending') => ['team-memory-candidates', orgId ?? null, status] as const,
    teamMemoryCandidateAudits: (orgId?: string | null, candidateId?: string | null) => ['team-memory-candidate-audits', orgId ?? null, candidateId ?? null] as const,
    observationCandidates: (orgId?: string | null, status = 'pending', subjectEmail: string | null = null) => ['observation-candidates', orgId ?? null, status, subjectEmail ?? null] as const,
    observationCandidateAudits: (orgId?: string | null, candidateId?: string | null) => ['observation-candidate-audits', orgId ?? null, candidateId ?? null] as const,
    approvals: (orgId?: string | null, domain: string | null = null, status: string | null = 'pending') => ['approvals', orgId ?? null, domain ?? null, status ?? null] as const,
    approvalDetail: (orgId?: string | null, id?: string | null) => ['approval-detail', orgId ?? null, id ?? null] as const,
    approvalAudits: (orgId?: string | null, id?: string | null) => ['approval-audits', orgId ?? null, id ?? null] as const,
    communicationPlanMe: (orgId?: string | null) => ['communication-plan-me', orgId ?? null] as const,
    communicationPlanMeAudits: (orgId?: string | null) => ['communication-plan-me-audits', orgId ?? null] as const,
    aiProfiles: (orgId?: string | null) => ['ai-profiles', orgId ?? null] as const,
    brainConfig: (orgId?: string | null) => ['brain-config', orgId ?? null] as const,
    selfSystem: (orgId?: string | null) => ['self-system', orgId ?? null] as const,
    tokenSources: (orgId: string, includeSecrets: boolean) => ['token-sources', orgId, includeSecrets ? 'secret' : 'public'] as const,
    orgs: ['orgs'] as const,
    org: (orgId: string) => ['org', orgId] as const,
    orgMembers: (orgId: string) => ['org-members', orgId] as const,
    orgInvitations: (orgId: string) => ['org-invitations', orgId] as const,
    pendingInvitations: ['pending-invitations'] as const,
    adminLicenses: ['admin-licenses'] as const,
    licenseOrganizations: ['license-organizations'] as const,
    sessionDownloads: (sessionId: string) => ['session-downloads', sessionId] as const,
}
