export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    onlineUsers: ['online-users'] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    typing: (sessionId: string) => ['typing', sessionId] as const,
    me: ['me'] as const,
    userPreferences: ['user-preferences'] as const,
    aiProfiles: (orgId?: string | null) => ['ai-profiles', orgId ?? null] as const,
    tokenSources: (orgId: string, includeSecrets: boolean) => ['token-sources', orgId, includeSecrets ? 'secret' : 'public'] as const,
    orgs: ['orgs'] as const,
    org: (orgId: string) => ['org', orgId] as const,
    orgMembers: (orgId: string) => ['org-members', orgId] as const,
    orgInvitations: (orgId: string) => ['org-invitations', orgId] as const,
    pendingInvitations: ['pending-invitations'] as const,
    adminLicenses: ['admin-licenses'] as const,
    licenseOrganizations: ['license-organizations'] as const,
    sessionDownloads: (sessionId: string) => ['session-downloads', sessionId] as const,
}
