import { randomUUID } from 'node:crypto'
import type { Pool, PoolClient } from 'pg'
import type { WorkerContext } from '../types'

// Phase 3C Conflict Scan：扫描同 personId 下"同 hypothesisKey 的 observation 候选"
// 或同 memoryRef 的 team memory 候选，写入 memory_conflict_candidates 供管理员仲裁。
// 设计稿：docs/design/k1-phase3-actor-aware-brain.md §4.C
// 硬边界：只生成候选，不自动合并、不自动废弃。
// 主键 subject_key 格式（与 server 端兼容）：
//   personal: obs:<personId>:<hypothesisKey>
//   team:     mem:<memoryRef>

export const CONFLICT_DETECTOR_VERSION = 'conflict-scan-v1'

export type ConflictScanResult = {
    scannedObservationGroups: number
    scannedTeamMemoryGroups: number
    createdConflictIds: string[]
    skippedDuplicateGroups: number
}

type ObservationGroupRow = {
    namespace: string
    org_id: string | null
    subject_person_id: string
    hypothesis_key: string
    candidate_ids: string[]
    summaries: string[]
    captured_ats: string[] // BIGINT comes back as string from pg
}

type TeamMemoryGroupRow = {
    namespace: string
    org_id: string | null
    memory_ref: string
    candidate_ids: string[]
    contents: string[]
    captured_ats: string[]
    actors: Array<string | null>
}

const OBSERVATION_GROUPS_SQL = `
    SELECT
        namespace,
        org_id,
        subject_person_id,
        hypothesis_key,
        ARRAY_AGG(id ORDER BY created_at) AS candidate_ids,
        ARRAY_AGG(summary ORDER BY created_at) AS summaries,
        ARRAY_AGG(created_at::TEXT ORDER BY created_at) AS captured_ats
    FROM observation_candidates
    WHERE status = 'pending'
      AND subject_person_id IS NOT NULL
    GROUP BY namespace, org_id, subject_person_id, hypothesis_key
    HAVING COUNT(*) >= 2
`

const TEAM_MEMORY_GROUPS_SQL = `
    SELECT
        namespace,
        org_id,
        memory_ref,
        ARRAY_AGG(id ORDER BY created_at) AS candidate_ids,
        ARRAY_AGG(content ORDER BY created_at) AS contents,
        ARRAY_AGG(created_at::TEXT ORDER BY created_at) AS captured_ats,
        ARRAY_AGG(proposed_by_email ORDER BY created_at) AS actors
    FROM team_memory_candidates
    WHERE status = 'pending'
      AND memory_ref IS NOT NULL
    GROUP BY namespace, org_id, memory_ref
    HAVING COUNT(*) >= 2
`

async function findOpenConflictId(
    client: PoolClient,
    args: { namespace: string; orgId: string | null; scope: 'personal' | 'team'; subjectKey: string },
): Promise<string | null> {
    const result = await client.query<{ id: string }>(
        `SELECT id FROM memory_conflict_candidates
         WHERE namespace = $1
           AND COALESCE(org_id, '') = COALESCE($2, '')
           AND scope = $3
           AND subject_key = $4
           AND status = 'open'
         LIMIT 1`,
        [args.namespace, args.orgId, args.scope, args.subjectKey],
    )
    return result.rows[0]?.id ?? null
}

async function insertConflict(
    client: PoolClient,
    args: {
        namespace: string
        orgId: string | null
        scope: 'personal' | 'team'
        subjectKey: string
        summary: string
        entries: Array<Record<string, unknown>>
        evidence: Record<string, unknown>
    },
): Promise<string> {
    const id = randomUUID()
    const now = Date.now()
    await client.query(
        `INSERT INTO memory_conflict_candidates (
            id, namespace, org_id, scope, subject_key, summary,
            entries, evidence, detector_version, status, created_at, updated_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8::jsonb, $9, 'open', $10, $10)`,
        [
            id,
            args.namespace,
            args.orgId,
            args.scope,
            args.subjectKey,
            args.summary,
            JSON.stringify(args.entries),
            JSON.stringify(args.evidence),
            CONFLICT_DETECTOR_VERSION,
            now,
        ],
    )
    await client.query(
        `INSERT INTO memory_conflict_audits (
            id, namespace, org_id, candidate_id, action, prior_status, new_status,
            resolution, actor_email, reason, payload, created_at
        ) VALUES ($1, $2, $3, $4, 'generated', NULL, 'open', NULL, NULL, $5, $6::jsonb, $7)`,
        [
            randomUUID(),
            args.namespace,
            args.orgId,
            id,
            'auto-generated by conflict-scan',
            JSON.stringify({ detectorVersion: CONFLICT_DETECTOR_VERSION }),
            now,
        ],
    )
    return id
}

function summarizeObservationGroup(row: ObservationGroupRow): string {
    return `Conflicting observation pool for ${row.subject_person_id}/${row.hypothesis_key}: ${row.candidate_ids.length} pending candidates`
}

function summarizeTeamMemoryGroup(row: TeamMemoryGroupRow): string {
    return `Conflicting team memory references for ${row.memory_ref}: ${row.candidate_ids.length} pending candidates`
}

function obsEntries(row: ObservationGroupRow): Array<Record<string, unknown>> {
    return row.candidate_ids.map((id, idx) => ({
        source: 'observation_candidate',
        memoryId: id,
        content: row.summaries[idx] ?? '',
        capturedAt: Number(row.captured_ats[idx] ?? 0),
        actor: null,
    }))
}

function teamEntries(row: TeamMemoryGroupRow): Array<Record<string, unknown>> {
    return row.candidate_ids.map((id, idx) => ({
        source: 'team_memory_candidate',
        memoryId: id,
        content: row.contents[idx] ?? '',
        capturedAt: Number(row.captured_ats[idx] ?? 0),
        actor: row.actors[idx] ?? null,
    }))
}

export async function scanForConflicts(pool: Pool): Promise<ConflictScanResult> {
    const result: ConflictScanResult = {
        scannedObservationGroups: 0,
        scannedTeamMemoryGroups: 0,
        createdConflictIds: [],
        skippedDuplicateGroups: 0,
    }

    const client = await pool.connect()
    try {
        const obsGroups = await client.query<ObservationGroupRow>(OBSERVATION_GROUPS_SQL)
        result.scannedObservationGroups = obsGroups.rows.length
        for (const row of obsGroups.rows) {
            const subjectKey = `obs:${row.subject_person_id}:${row.hypothesis_key}`
            const existing = await findOpenConflictId(client, {
                namespace: row.namespace,
                orgId: row.org_id,
                scope: 'personal',
                subjectKey,
            })
            if (existing) {
                result.skippedDuplicateGroups += 1
                continue
            }
            const id = await insertConflict(client, {
                namespace: row.namespace,
                orgId: row.org_id,
                scope: 'personal',
                subjectKey,
                summary: summarizeObservationGroup(row),
                entries: obsEntries(row),
                evidence: { kind: 'observation', candidateIds: row.candidate_ids },
            })
            result.createdConflictIds.push(id)
        }

        const teamGroups = await client.query<TeamMemoryGroupRow>(TEAM_MEMORY_GROUPS_SQL)
        result.scannedTeamMemoryGroups = teamGroups.rows.length
        for (const row of teamGroups.rows) {
            const subjectKey = `mem:${row.memory_ref}`
            const existing = await findOpenConflictId(client, {
                namespace: row.namespace,
                orgId: row.org_id,
                scope: 'team',
                subjectKey,
            })
            if (existing) {
                result.skippedDuplicateGroups += 1
                continue
            }
            const id = await insertConflict(client, {
                namespace: row.namespace,
                orgId: row.org_id,
                scope: 'team',
                subjectKey,
                summary: summarizeTeamMemoryGroup(row),
                entries: teamEntries(row),
                evidence: { kind: 'team_memory', candidateIds: row.candidate_ids },
            })
            result.createdConflictIds.push(id)
        }
    } finally {
        client.release()
    }

    return result
}

export async function handleConflictScan(_data: unknown, ctx: WorkerContext): Promise<void> {
    try {
        const result = await scanForConflicts(ctx.pool)
        if (result.createdConflictIds.length > 0 || result.skippedDuplicateGroups > 0) {
            console.log(
                `[conflictScan] obsGroups=${result.scannedObservationGroups}` +
                ` teamGroups=${result.scannedTeamMemoryGroups}` +
                ` created=${result.createdConflictIds.length}` +
                ` skippedDup=${result.skippedDuplicateGroups}`,
            )
        }
    } catch (err) {
        console.error('[conflictScan] scan failed:', err)
    }
}
